### ISSUE TITLE
欲しいスタンプ画像の列挙

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/kokoro-io#10]
LINEみたいなスタンプ送信機能を実装する予定なので、初期のスタンプ画像としてほしいものを列挙
- [ ] Vim
- [ ] Emacs
- [ ] ﾓﾓﾝｶﾞ
- [ ] ﾏﾝﾎﾞｳ
- [ ] ｳｰﾊﾟｰﾙｰﾊﾟｰ
- [ ] mattn
- [ ] 便利

**Comment by 0xBADDCAFE** [comment]
- [ ] いらすとや

**Comment by supermomonga** [comment]
それだ！

**Comment by supermomonga** [comment]
とりあえず一旦とじる

**Comment by 0xBADDCAFE** [comment]
:dancing_men:
