### ISSUE TITLE
inherited_resourcesやめたい

### ISSUE THREAD

**Issue by mtwtkman** [supermomonga/kokoro-io#124]
Rails4以降は使わなくていいし、そもそもいらないぽい
[:ref](https://github.com/josevalim/inherited_resources#deprecation-notice)

**Comment by mtwtkman** [comment]
> Rails4以降は使わなくていいし、そもそもいらないぽい
この根拠となっていたはずの文言が今なくなってるので閉じます

**Comment by supermomonga** [comment]
脱 InheritedResources 是非やりたいので reopen しときます

- 得られるDRYに対して過度な隠蔽（少し挙動を変えたい時にInheritedResourcesの仕様読むことになる）
- InheritedResources 使わずに普通に書いたほうがコードの意図がわかりやすい

**Comment by supermomonga** [comment]
完了した
