### ISSUE TITLE
画面作成

### ISSUE THREAD

**Issue by kamichidu** [supermomonga/kokoro-io#125]
細細やり始めました。
とりあえずSPAの叩き台作ってます。

なんか進捗あればここに書いていきます。

**Comment by kamichidu** [comment]
デザインセンス、皆無。
やはりオーソドックスなものが良いかしら...

![gamen](https://cloud.githubusercontent.com/assets/571248/20760373/36172bd4-b763-11e6-9127-10b2bc9556c2.png)

**Comment by mtwtkman** [comment]
kamichidu++

[gitter](https://gitter.im/kokoro_io/Lobby)で喧々諤々しています

**Comment by supermomonga** [comment]
チャット画面は基本的にオーソドックスなのにする予定（ほぼ Lingr と同じ）

**Comment by kamichidu** [comment]
ある程度できてきたし、このIssueは閉じてしまって良さそう。
