### ISSUE TITLE
Bootstrap javascript library の使用

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/kokoro-io#161]
jQueryの読み込みはできるけどjQueryプラギンとしてjQueryオブジェクトにメソッド生やすのができてないっぽい

使いたいライブラリ

- bootstrap/alert
- bootstrap/collapse
- bootstrap/dropdown
- bootstrap/tooltip
- bootstrap/popover

### 右上のドロップダウン

![image](https://cloud.githubusercontent.com/assets/377137/25338258/911ccbcc-2939-11e7-966f-b520c6d64c9d.png)

### ルーム詳細ページでのユーザ情報ポップオーバー

![image](https://cloud.githubusercontent.com/assets/377137/25338267/9af65d2a-2939-11e7-89c2-bbf66b278b39.png)

**Comment by kamichidu** [comment]
週末などにやろう

**Comment by supermomonga** [comment]
https://github.com/supermomonga/kokoro-io/commit/a63e7b9bac0783756f2fb89c60175a4a68f0c593

`webpack.ProvidePlugin` を使うことで jquery-ujs は使えるようになったが、Bootstrapの方は以前使えず

**Comment by supermomonga** [comment]
kamichidu さんがやってくれた
