### ISSUE TITLE
単一ファイルコンポーネントをやめたい

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/kokoro-io#167]
https://jp.vuejs.org/v2/guide/single-file-components.html#関心の分離について

>単一ファイルコンポーネントのアイデアが気に入らなくても、JavaScript と CSS を別々のファイルに分けることで、ホットリロードとプリコンパイル機能を活用できます:

```html
<!-- my-component.vue -->
<template>
  <div>This will be pre-compiled</div>
</template>
<script src="./my-component.js"></script>
<style src="./my-component.css"></style>
```

----

とある通り、ファイルを分離したい。

## 理由

単一のバッファで上手く複数の言語をハンドリングできるエディタが少ない。例えば Emacs では mmm-mode を用いることでシンタックスハイライトは対応できるが、補完エンジンをカーソル位置をベースに切り替えることなどを考え出すとつらい

**Comment by supermomonga** [comment]
ディレクトリ構成をどうするか

---

```
assets/javascripts/views/hoge.vue
assets/javascripts/views/hoge.ts
assets/javascripts/views/hoge.scss
```

---

```
assets/javascripts/templates/hoge.vue
assets/javascripts/scripts/hoge.ts
assets/javascripts/styles/hoge.scss
```

---

その他

**Comment by mtwtkman** [comment]
javascripts/<コンポーネント名>/の下に
template.vue
script.js
style.scss

でいいかと

**Comment by kamichidu** [comment]
@mtwtkman ++

**Comment by supermomonga** [comment]
🆗

**Comment by supermomonga** [comment]
とりあえず一旦閉じる
