### ISSUE TITLE
通知音のON/OFF

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/kokoro-io#185]
通知音のON/OFFを切り替えられるようにして、設定値を記憶する

**Comment by kamichidu** [comment]
App.config.isSoundEnabled()を実装してあり、通知音を再生させる箇所はON/OFFを見るようにしてあります。
残りは、App.config.setSoundEnabled(false)をどこかで呼んでやるだけです。

**Comment by supermomonga** [comment]
わーい

それ用のUIパーツ実装します

**Comment by supermomonga** [comment]
できた気がする

@kamichidu 暇な時にレビューお願いします

**Comment by kamichidu** [comment]
レビューしました。1点のみ問題あったので、コメントつけています。

**Comment by supermomonga** [comment]
なるほど、直します！

**Comment by supermomonga** [comment]
done
