### ISSUE TITLE
scrollToLatestTalk() の挙動がおかしい？

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/kokoro-io#190]
各部屋について、初回表示時は scrollToLatestTalk() が効いてない気がする。

**Comment by supermomonga** [comment]
メッセージの描画完了前にスクロールしてしまってるのかな

**Comment by mtwtkman** [comment]
profiler で見張ったけどそもそも `messageReceived` が発火してないっぽ

**Comment by supermomonga** [comment]
`roomChanged` で `changeRoom` が呼ばれてそこで `scrollToLatestTalk` 呼んでるはず

**Comment by mtwtkman** [comment]
完全に理解した
