### ISSUE TITLE
webpack-dev-server の導入

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/kokoro-io#195]
一度コンパイルエラーが出ると watch してるプロセスが反応しなくなる気がする（プロセス自体は生きてそう）

**Comment by kamichidu** [comment]
あー、ビルドこけるとwatchまで行かずにプロセス死にますね。直します

**Comment by kamichidu** [comment]
起動時の話

**Comment by supermomonga** [comment]
便利

**Comment by supermomonga** [comment]
これって直ったんだっけ

**Comment by kamichidu** [comment]
まだ手を入れてないです。
docker内でコンパイルしている関係で、windowsやmacだとホストファイルシステムの変更がコンテナ内ファイルシステムに反映されなくなる場合もあるんですけど、今回は恐らくnpm scriptの変更で改善すると思います。

**Comment by kamichidu** [comment]
この問題、先日再現しました。
今ってtsのコンパイルはwebpack --watchでやってるんですが、手元ではwebpack-dev-serverを代替で利用することで再現しなくなった。
なのでwebpack-dev-serverの導入ができたら直る可能性高い。

**Comment by mtwtkman** [comment]
これ、[このプルリク](https://github.com/supermomonga/kokoro-io/pull/271)で対応された気がする
