### ISSUE TITLE
可能であれば screen_name でなく id を使う

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/kokoro-io#213]
チャット中に screen_name が変化することは十分あり得るので、可変である screen_name でなく不変である id を使ったほうがいい気がしてきた。

JavaScript 部分や REST API など。

**Comment by mtwtkman** [comment]
friendly_id 使わないってこと？

**Comment by supermomonga** [comment]
エンドユーザーに直接露出する部分のみに使う感じ。プロフィールのURLとか。

APIとかの、露出しない部分に関しては不変であるidを使いたい

**Comment by mtwtkman** [comment]
nrhd

**Comment by mtwtkman** [comment]
```
(id, screen_name)
(1, hoge) -update-> (1, fuga)
(2, fuga) -update-> (2, piyo)
```
users/fuga は id=1 のユーザーを指す。
users/hoge はもはや存在しないが、[history](http://norman.github.io/friendly_id/FriendlyId/History.html) アドオンを使うことで見つけることができそう

=> screen_name が変更されようが friendly_id は主キーのプロキシというだけなのでユーザーを一意に特定することに影響はないはず。この対応は不要な気がする

**Comment by supermomonga** [comment]
主にroom関連で不整合が起きそうな気がする。

- Room1(id=1, screen_name=foo)
- Room2(id=2, screen_name=bar)

この状態でチャット画面を開いて、その後部屋の screen_name が変わって

- Room1(id=1, screen_name=foo2)
- Room2(id=2, screen_name=foo)

になった時、クライアント側のいろんな箇所で動作が怪しくなる気がする。

- `rooms['foo']` で引けるroomはちゃんとRoom1からRoom2に切り替わるのか？
- RoomNへの新しいメッセージを受信した時、ちゃんとRoomNに追加できるのか？

など、websocketでサーバー側から通知飛ばせば対応はできそうだけど、コスト考えると最初から内部ではidで管理しておいたほうが素直な実装にできそうな気がする。

あと、history についてはscreen_nameが他のレコードに再利用された場合に不整合起きそうな予感がする

**Comment by supermomonga** [comment]
Slackのチャットでもそうで、基本的にチャンネル名やユーザーへのリプライにおいてその時のスクリーンネームはあくまでテキスト表示上のデータとしてだけ保持しておいて、実際は対象となるレコードのIDを記録していて、レコードの参照はスクリーンネームでなくそのIDを利用してる。

https://api.slack.com/docs/message-formatting#linking_to_channels_and_users

**Comment by mtwtkman** [comment]
なるほど

**Comment by supermomonga** [comment]
とりあえずREST API側、web client側できた気がするのでclose
