### ISSUE TITLE
ログインセッションの持続時間

### ISSUE THREAD

**Issue by kamichidu** [supermomonga/kokoro-io#224]
今って恐らく1日になっている？
個人的にはオープンチャットなので、セッションが長く残るようにしたほうが使い勝手が良い気がする。
もしくはこのまま、OAuth2のRefreshToken対応（例）を待つか。

**Comment by supermomonga** [comment]
ヨッシャ伸ばすぞ

**Comment by kamichidu** [comment]
かっこいい

**Comment by supermomonga** [comment]
NOBASHITA

**Comment by supermomonga** [comment]
Cookieの有効期限12ヶ月にした
