### ISSUE TITLE
権限付与機能

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/kokoro-io#235]
メンバーへの権限付与機能

---

参考： https://github.com/supermomonga/kokoro-io/wiki/Authorities

**Comment by mtwtkman** [comment]
demote が administrator にしか許可されてないけど promote と非対称なの違和感ある。

**promote**
自分より下の権限に対して可能
- administrator は (maintainer | member) なユーザーを (administrator | maintainer) に昇格できる
- maintainer は member なユーザーを maintainer に昇格できる

**demote**
自分以下の権限に対して可能
- administrator は (administrator | maintainer) なユーザーを (maintainer | member) に降格できる
- maintainer は maintainer なユーザーを member に降格できる

でいいんじゃないかな

**Comment by supermomonga** [comment]
同格ユーザーを demote できるとまずいかなと思って現状の権限設定になってるけど、確かにそれだと administrator は増えるしかできなくて不味いか。

>でいいんじゃないかな

というわけで +1

**Comment by mtwtkman** [comment]
> 同格ユーザーを demote できるとまずいかな

これは確かにそうだと思います。
思いつくまずそうな事例
- ヤバい人が administrator になってしまい、他の administrator をガンガン降格させまくる
- 2人しか administrator のいない状態でお互いに同時のタイミングで降格リクエストをした場合(そもそもデータ競合起きそうだけど、論理的には administrator 不在)

多分もっとも安全なのは部屋の作者(=デフォルトの administrator)を不変の管理者として、この人に対しては何人たりとも demote 不可とするという設計かな。
レアケースではとか言われるとはい、という感じがする

**Comment by supermomonga** [comment]
>ヤバい人が administrator になってしまい、他の administrator をガンガン降格させまくる

そうそう、主にこれを想定して現状の権限設定にしてあった

しかし極端な話、最初に存在した administrator （部屋の作成者）が後々ヤバくなって部屋を破壊する可能性などもあるので、administrator がトチ狂った行動をするかもというのは避けられないリスクとして許容するしかない気がしてきた。

administrator は基本的に全権限持つことになるので、気軽に増やさないべきというのがありそう（基本的には maintainer であれば部屋のメンテは十分できる）。

>2人しか administrator のいない状態でお互いに同時のタイミングで降格リクエストをした場合(そもそもデータ競合起きそうだけど、論理的には administrator 不在)

これは悲観的ロックすればいいかなー

**Comment by mtwtkman** [comment]
> administrator がトチ狂った行動をするかもというのは避けられないリスクとして許容するしかない気がしてきた。

まあそうね。人は突然高まるということが知られているし利用者側の責任をシステムでどうのできることではないので考慮する必要はなさそう。

相互の更新について、これはそう頻繁に起きないだろうと思っててとりあえずは楽観的でいいのではという気持ち。自分で挙げといてアレなんだけど。

話をややこしくしてごめんという感じなのでとりあえずさっき合意もらった promote/demote の仕様でやっていこう
