### ISSUE TITLE
GrapeによるAPI作成

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/kokoro-io#60]
[grape-swagger](https://github.com/ruby-grape/grape-swagger) でドキュメントも生成

**Comment by mtwtkman** [comment]
直近やる必要がないので閉じますね。

**Comment by mtwtkman** [comment]
[参考記事](http://www.bokukoko.info/entry/2016/01/01/Grape_on_Rails_%E3%81%A7_API_%E9%96%8B%E7%99%BA)

**Comment by mtwtkman** [comment]
swagger_doc にもアクセス制限かけないといけないんだな。やらねえと

**Comment by supermomonga** [comment]
下地は揃えたのでClose
